// Generated by CoffeeScript 1.3.3
var Entity;

Entity = (function() {

  function Entity(x, y) {
    this.setPosition(x, y);
  }

  Entity.prototype.setPosition = function(x, y) {
    this.pos = {
      x: x,
      y: y
    };
    return this.pos;
  };

  return Entity;

})();

module.exports = Entity;
