// Generated by CoffeeScript 1.3.3
var Entity, LivingEntity, STATE,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Entity = require('./entity');

STATE = {
  DEAD: 0,
  UNCONSCIOUS: 1,
  LIVING: 2
};

LivingEntity = (function(_super) {

  __extends(LivingEntity, _super);

  function LivingEntity(x, y) {
    LivingEntity.__super__.constructor.call(this, x, y);
    this.health = this.maxHealth = 100;
    this.state = STATE.LIVING;
  }

  return LivingEntity;

})(Entity);

module.exports = LivingEntity;
