// Generated by CoffeeScript 1.3.3
var LivingEntity, Player,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LivingEntity = require('./living');

Player = (function(_super) {

  __extends(Player, _super);

  function Player(x, y, name) {
    this.name = name;
    Player.__super__.constructor.call(this, x, y);
    this.health = 100;
    this.inventory = [];
  }

  Player.prototype.giveItem = function(item) {
    return this.inventory.push(item);
  };

  Player.prototype.toString = function() {
    return "Player " + this.name + ": " + this.health + "hp @ (" + this.pos.x + ", " + this.pos.y + ")\n";
  };

  return Player;

})(LivingEntity);

module.exports = Player;
