// Generated by CoffeeScript 1.3.3
var LivingEntity, Zombie,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LivingEntity = require('./living');

Zombie = (function(_super) {

  __extends(Zombie, _super);

  function Zombie(x, y) {
    Zombie.__super__.constructor.call(this, x, y);
  }

  Zombie.prototype.attack = function(player) {
    var damage;
    damage = Math.floor(Math.random() * 5);
    return player.health -= damage;
  };

  Zombie.prototype.toString = function() {
    return "Zombie: " + this.name + "hp @ (" + this.pos.x + ", " + this.pos.y + ")\n";
  };

  return Zombie;

})(LivingEntity);

module.exports = Zombie;
